### ISSUE TITLE
Alpha TV CY

### ISSUE THREAD

**Issue by ROBGagn** [iptvnikolas/Nikki-TVM3U8#2]
Your last updated link for Alpha TV CY is not working... 

http://l4.cloudskep.com/alphacyp/acy/playlist.m3u8?wmsAuthSign=c2VydmVyX3RpbWU9Mi8xOS8yMDIzIDg6MzU6NTIgQU0maGFzaF92YWx1ZT1zMFB1ZVhZOGlSdU03YzRHOS9FVmN3PT0mdmFsaWRtaW51dGVzPTM2MA==

After some time the token expires...

**Comment by iptvnikolas** [comment]
It's not working due to a temporary technical problem
