### ISSUE TITLE
It is better to enter the Alpha Cyprus website and press F12 to get the link to m3u8 of the laptop.

### ISSUE THREAD

**Issue by ROBGagn** [iptvnikolas/Nikki-TVM3U8#4]
It is better to enter the Alpha Cyprus website and press F12 to get the link to m3u8 of the laptop.

_Originally posted by @iptvnikolas in https://github.com/iptvnikolas/Nikki-TVM3U8/issues/1#issuecomment-1758490867_

The issue is that you have to do it every time you want to watch. I'm looking for a token auto-update repo.

**Comment by iptvnikolas** [comment]
I downloaded from my computer to website alphacyprus.cy/live
http://l4.cloudskep.com/alphacyp/alphacy/playlist.m3u8
https://l4.cloudskep.com/alphacyp/alphacy/playlist.m3u8
http://l4.cloudskep.com/alphacy/alphacy/playlist.m3u8
https://s1.cystream.net/live/alphacy/playlist.m3u8?wmsAuthSign=c2VydmVyX3RpbWU9Mi8xOS8yMDIzIDg6MzU6NTIgQU0maGFzaF92YWx1ZT1zMFB1ZVhZOGlSdU03YzRHOS9FVmN3PT0mdmFsaWRtaW51dGVzPTM2MA==
http://l4.cloudskep.com/alphacyp/alphacy/playlist.m3u8!wmsAuthSign=c2VydmVyX3RpbWU9Mi8xOS8yMDIzIDg6MzU6NTIgQU0maGFzaF92YWx1ZT1zMFB1ZVhZOGlSdU03YzRHOS9FVmN3PT0mdmFsaWRtaW51dGVzPTM2MA==

**Comment by iptvnikolas** [comment]
You have Cypriot VPN?
