### ISSUE TITLE
You have Cypriot VPN?

### ISSUE THREAD

**Issue by ROBGagn** [iptvnikolas/Nikki-TVM3U8#5]
You have Cypriot VPN?

_Originally posted by @iptvnikolas in https://github.com/iptvnikolas/Nikki-TVM3U8/issues/4#issuecomment-1759706052_

Yes of course, I even tried with different ones... But the token expires after a few minutes.

**Comment by iptvnikolas** [comment]
I have too but mine never opens Omega.
